### PR TITLE
add conditional exports entries

### PR DESCRIPTION
**Pull request by cometkim**

### CODE REVIEW

**Comment by arcanis** [comment]
@cometkim I had to revert this PR: https://github.com/arcanis/clipanion/issues/139

If we want to re-land it I think this time we'll need to add tests to make sure that the ESM build works fine (I took a quick look, and I think the idea would be to add an `exports` entry for `./platform` which would point to either `node.ts` or `browser.ts` based on whether the `node` condition is set; Rollup might also need to be upgraded).

**Comment by cometkim** [comment]
OK I will try again

**Comment by cometkim** [comment]
@arcanis Can you push your reverted commit to `master`?

**Comment by artechventure** [comment]
It seems that exports map in package.json inside subpath like `./platform` is not well respected. What about using subpath imports? I think that will solve this `platform` problem better.

**Comment by cometkim** [comment]
@arcanis New PR here #140

**Pull request merged**
