### PR TITLE
remove unused variable and code optimization

### PR DESCRIPTION
**Pull request by MrJithil**
Completed a TODO task

### CODE REVIEW

**Comment by MrJithil** [comment]
CC: @arcanis

**Comment by MrJithil** [comment]
Still pending?

**Comment by MrJithil** [comment]
Can we merge it?

**Comment by arcanis** [comment]
I prefer not - as the comment says, there's likely a bug here, and just removing the comment and the usage feels the less ideal option (compared to figuring out for sure what's the right behavior).

Given that your change has no functional impact, I prefer to keep the strange code as it is until we figure it out.

**Pull request closed without merging**
